### ISSUE TITLE
Explode sources in data files

### ISSUE THREAD

**Issue by hrbonz** [gams/openkongqi#34]
Create a folder for sources, one file per website should be enough.
We should by the same token unify the "key" format we're using for UUIDs and sources, I think we should us a '/' as separator everywhere.

**Comment by hrbonz** [comment]
There's quite a lot of refactoring to do here:
* `openkongqi.utils` should have the following functions:
    * `SEP` should be '/'
    * `load_tree()` that loads a generic tree of data files on disk, this is essentially a copy of `load_sources()` without the `sep` argument.
    * `get_uuid()` that is a copy of `openkongqi.stations.get_uuid()`
* everything referencing uuid instead of station should be renamed to station (for example, `_STATIONS_UUID_MAP` becomes `_STATIONS_MAP`
* rename `data/uuid` to `data/stations`

**Comment by eddowh** [comment]
Slight problem. When I try to load my sources in `openkongqi.conf`, I had to import `load_tree` and `source_loader` from `openkongqi.utils`.

However `openkongqi.utils` imports `settings` from `openkongqi.conf` because of the random user agent string function. So both modules are dependent on each other and none would be loaded.

I think we might need to move the `load_tree` function out of `openkongqi.utils` as to not introduce collisions.

**Comment by hrbonz** [comment]
Ah the good old circular import issue!!
