### ISSUE TITLE
Random user agent

### ISSUE THREAD

**Issue by hrbonz** [gams/openkongqi#7]
Create a data file of user agents to feed a random user-agent function.
Use this to feed `HTTPSource` requests.

Covers #6

**Comment by eddowh** [comment]
[List of data strings](http://useragentstring.com/pages/useragentstring.php)

Apparently, there is a package called [fake-useragent](https://pypi.python.org/pypi/fake-useragent) on PyPI that does this work but I don't think it's maintained anymore since the build is failing?

Speaking of which, will the variable timing for crawling as mentioned in #6 be achieved with Celery's task runner?

**Comment by hrbonz** [comment]
I seem to remember you can implement your own scheduling class for celery, I think that's the way we'll go for #6.

The fake-useragent tests look broken because the badges are wrong, he fixed it in the github and didn't update the package on pypi I suppose. Code version was bumped to 0.0.9 on github.

See comments on your code.
